name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          working-directory: ./dist
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - uses: actions/setup-node@v2

      - run: npm install -g @vercel/cli
      - run: vercel --token ${{ secrets.VERCEL_TOKEN }} --scope eustache --prod
